# Preprocessing configuration for SAR land masking and normalization

# Paths - promoted from paths block, interpolated from global config
land_shapefile: "data/land_mask/ne_10m_land.shp"
download_dir: ${paths.download_dir}
processed_dir: ${paths.processed_dir}
preview_dir: ${paths.preview_dir}
temp_dir: ${paths.temp_dir}

# Processing parameters
clip_percentile: 99.9
dilate_px: 12
convert_to_db: true
save_masked: true
masked_dtype: "float32"  # float32, uint16, or uint8
compress: "DEFLATE"  # DEFLATE, ZSTD, LZW, etc.
processed_suffix: ""  # suffix to append to processed filenames (e.g. "_processed")
